'use strict';


// Wit.ai parameters
//const WIT_TOKEN = "65TEIYTXAZPOCEWCCPRDV354WT4KZVSW";
// const WIT_TOKEN = "QYX4NYOZRG3BJR6AX6RXU4QU4W5X67FZ";
const WIT_TOKEN = "JGO74IBMTRUI5SZCALHPJYKVNL6DIEHI"; //selekt1
if (!WIT_TOKEN) {
  throw new Error('missing WIT_TOKEN');
}

// Messenger API parameters
// const FB_PAGE_TOKEN = "EAAOm46andbEBAEgJDpZAR39eikdUIuK2cZB0gtGuYyW8OElEiRxZCpR63BZCi9wbq7owKAnqsCLVetzahm5vKzLioemXV7ZBKQ1ai4wZBZC05CivoI5Tl5PFtvGZAvr7DPMBEFOpSSdIR9YPZAWAEgAlXoSLrc0VkLPOM41gnjofTqwZDZD";
const FB_PAGE_TOKEN = "EAAHZAtBXmLWwBAPPLqS7igEc7kdzVbPv0aRgOUMDZCyKQyUZApR1V8qkPuxZCODCPcRYKdBxEJBbZCHZAZAYPYM9AFtZCZArVbth1ykBxCaFOmlofkWNZCVDBVmHZAKGL4OvZCj7AZCpHl9ZAYq58atEXzQaccij7kSxGvshnJrpZBVhWDCLQZDZD";

var FB_VERIFY_TOKEN = "hello_bot";
if (!FB_VERIFY_TOKEN) {
  FB_VERIFY_TOKEN = "hello_bot";
}

module.exports = {
  WIT_TOKEN: WIT_TOKEN,
  FB_PAGE_TOKEN: FB_PAGE_TOKEN,
  FB_VERIFY_TOKEN: FB_VERIFY_TOKEN,
};
